package model

import "strings"

const (
	PREDICATE_CCSDS_OMM_VERS      string = "CCSDS_OMM_VERS"
	PREDICATE_COMMENT             string = "COMMENT"
	PREDICATE_CREATION_DATE       string = "CREATION_DATE"
	PREDICATE_ORIGINATOR          string = "ORIGINATOR"
	PREDICATE_OBJECT_NAME         string = "OBJECT_NAME"
	PREDICATE_OBJECT_ID           string = "OBJECT_ID"
	PREDICATE_CENTER_NAME         string = "CENTER_NAME"
	PREDICATE_REF_FRAME           string = "REF_FRAME"
	PREDICATE_TIME_SYSTEM         string = "TIME_SYSTEM"
	PREDICATE_MEAN_ELEMENT_THEORY string = "MEAN_ELEMENT_THEORY"
	PREDICATE_EPOCH               string = "EPOCH"
	PREDICATE_MEAN_MOTION         string = "MEAN_MOTION"
	PREDICATE_ECCENTRICITY        string = "ECCENTRICITY"
	PREDICATE_INCLINATION         string = "INCLINATION"
	PREDICATE_RA_OF_ASC_NODE      string = "RA_OF_ASC_NODE"
	PREDICATE_ARG_OF_PERICENTER   string = "ARG_OF_PERICENTER"
	PREDICATE_MEAN_ANOMALY        string = "MEAN_ANOMALY"
	PREDICATE_EPHEMERIS_TYPE      string = "EPHEMERIS_TYPE"
	PREDICATE_CLASSIFICATION_TYPE string = "CLASSIFICATION_TYPE"
	PREDICATE_NORAD_CAT_ID        string = "NORAD_CAT_ID"
	PREDICATE_ELEMENT_SET_NO      string = "ELEMENT_SET_NO"
	PREDICATE_REV_AT_EPOCH        string = "REV_AT_EPOCH"
	PREDICATE_BSTAR               string = "BSTAR"
	PREDICATE_MEAN_MOTION_DOT     string = "MEAN_MOTION_DOT"
	PREDICATE_MEAN_MOTION_DDOT    string = "MEAN_MOTION_DDOT"
	PREDICATE_SEMIMAJOR_AXIS      string = "SEMIMAJOR_AXIS"
	PREDICATE_PERIOD              string = "PERIOD"
	PREDICATE_APOAPSIS            string = "APOAPSIS"
	PREDICATE_PERIAPSIS           string = "PERIAPSIS"
	PREDICATE_OBJECT_TYPE         string = "OBJECT_TYPE"
	PREDICATE_RCS_SIZE            string = "RCS_SIZE"
	PREDICATE_COUNTRY_CODE        string = "COUNTRY_CODE"
	PREDICATE_LAUNCH_DATE         string = "LAUNCH_DATE"
	PREDICATE_SITE                string = "SITE"
	PREDICATE_DECAY_DATE          string = "DECAY_DATE"
	PREDICATE_FILE                string = "FILE"
	PREDICATE_GP_ID               string = "GP_ID"
	PREDICATE_TLE_LINE0           string = "TLE_LINE0"
	PREDICATE_TLE_LINE1           string = "TLE_LINE1"
	PREDICATE_TLE_LINE2           string = "TLE_LINE2"
)

var PredicatePossibleValues = []string{
	PREDICATE_CCSDS_OMM_VERS,
	PREDICATE_COMMENT,
	PREDICATE_CREATION_DATE,
	PREDICATE_ORIGINATOR,
	PREDICATE_OBJECT_NAME,
	PREDICATE_OBJECT_ID,
	PREDICATE_CENTER_NAME,
	PREDICATE_REF_FRAME,
	PREDICATE_TIME_SYSTEM,
	PREDICATE_MEAN_ELEMENT_THEORY,
	PREDICATE_EPOCH,
	PREDICATE_MEAN_MOTION,
	PREDICATE_ECCENTRICITY,
	PREDICATE_INCLINATION,
	PREDICATE_RA_OF_ASC_NODE,
	PREDICATE_ARG_OF_PERICENTER,
	PREDICATE_MEAN_ANOMALY,
	PREDICATE_EPHEMERIS_TYPE,
	PREDICATE_CLASSIFICATION_TYPE,
	PREDICATE_NORAD_CAT_ID,
	PREDICATE_ELEMENT_SET_NO,
	PREDICATE_REV_AT_EPOCH,
	PREDICATE_BSTAR,
	PREDICATE_MEAN_MOTION_DOT,
	PREDICATE_MEAN_MOTION_DDOT,
	PREDICATE_SEMIMAJOR_AXIS,
	PREDICATE_PERIOD,
	PREDICATE_APOAPSIS,
	PREDICATE_PERIAPSIS,
	PREDICATE_OBJECT_TYPE,
	PREDICATE_RCS_SIZE,
	PREDICATE_COUNTRY_CODE,
	PREDICATE_LAUNCH_DATE,
	PREDICATE_SITE,
	PREDICATE_DECAY_DATE,
	PREDICATE_FILE,
	PREDICATE_GP_ID,
	PREDICATE_TLE_LINE0,
	PREDICATE_TLE_LINE1,
	PREDICATE_TLE_LINE2,
}

type Predicate struct {
	Name  string
	Value string
}

func (p Predicate) ToPath() string {
	p.Value = strings.ReplaceAll(p.Value, "=", "")
	return "/" + p.Name + "/" + p.Value
}
