run:
  timeout: "5m"
  issue-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false
  go: "1.18"
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true
  sort-results: true
linters:
  disable-all: true
  fast: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - varcheck
    - bodyclose
    - cyclop
    - decorder
    - depguard
    - errname
    - exhaustive