build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./go-spacetrack ./...

debug:
	CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./go-spacetrack -gcflags="all=-N -l" ./...
	@dlv --listen=:2345 --headless=true --api-version=2 exec ./go-spacetrack -- --config-file /tmp/spacetrack.yml
